name: release
on: 
  push:
    branches:
      - main
    paths:
        - packages/browser/manifest.json

jobs:
  release:
    runs-on: ubuntu-latest #通常はubuntu-latestにすることが多い、ubuntuはLinuxを用いたOSの一つで、ci/cd時にもよく使われる

    steps:
      - name: checkout repository
        uses: actions/checkout@v7 #v3だと古い

      - name: Use Node.js
        uses: actions/setup-node@v7 #v4は2024年ごろの主流
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies #continuous intengrationではなくclean install
        run: npm ci

      - name: build package
        run: npm run build

      - name: run tests
        run: npm test

      - name: compress dist folder
        run: node compress.js

      - name: Submit
        run: |
          npx chrome-webstore-upload-cli@4 --source extension.zip
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          PUBLISHER_ID: ${{ secrets.PUBLISHER_ID }}